# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aum Illuminatus diary
email: aumilluminatus@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  driven by man who suddenly noticed he understood something about who every human is, but nobody knows he is
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aumilluminatus.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: aumilluminatus

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
